### ISSUE TITLE
vue-cli3配置项不生效的问题

### ISSUE THREAD

**Issue by linzhongxian** [hyy1115/style-vw-loader#1]
你好，当我在vue-cli3使用本loader想更改配置项时，发现配置项没有生效，具体如下：
vue.config.js的配置：
> chainWebpack: config => {
>     config.module
>       .rule('vue')
>       .test(/\.vue$/)
>       .use('style-vw-loader')
>       .loader('style-vw-loader')
>       .options({
>         viewportWidth: 375,
>       }).end()
>   },

然后我在标签的style里面写padding:30px得到的是4vw，之后我把配置项去掉后，得到的还是4vw，我不清楚是否是我配置写错了，如果是的话，作者能不能更新一个修改配置的写法呢？

之后我把源码拷贝出来本地调试，将获取options的代码位置调到导出函数里面时，配置就生效了：

> module.exports = function (source) {
>   const opts = loaderUtils.getOptions(this)
>   const defaults = Object.assign({}, defaultsProp, opts)
   .....}

所以不知道是不是源代码这里有问题还是我的配置写法有问题

**Comment by hyy1115** [comment]
你的是对的。
