### ISSUE TITLE
动态style应该怎么处理

### ISSUE THREAD

**Issue by iamwelk** [hyy1115/style-vw-loader#3]
在vue模板中使用了`:style="{fontSize: 20px}"`这种用法的能处理吗

**Comment by iamwelk** [comment]
目前是用`createPxReplace`自己封装了一个方法

**Comment by hyy1115** [comment]
> 目前是用`createPxReplace`自己封装了一个方法

也许你可以把解法贡献出来。

**Comment by iamwelk** [comment]
下面是根据分享总结出来的方案
https://www.yuque.com/louwenkang/ypz71r/ny1xs3
